// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGYlUOgtcjETbJVZUSXhQOI7vbS3BRsnI',
    appId: '1:309013368429:android:f5a285ae35b1cc2e093964',
    messagingSenderId: '309013368429',
    projectId: 'certify-72d28',
    storageBucket: 'certify-72d28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBgbkfNiNaMoygUkTHTfSjqnSwKwgl5Zk',
    appId: '1:309013368429:ios:3b52d0d5df48ef82093964',
    messagingSenderId: '309013368429',
    projectId: 'certify-72d28',
    storageBucket: 'certify-72d28.firebasestorage.app',
    androidClientId: '309013368429-f7am49tqcdq7dli09ofhf3a2hf8i6gv8.apps.googleusercontent.com',
    iosClientId: '309013368429-cchj00c0sespabk01mduas725h8i4jb6.apps.googleusercontent.com',
    iosBundleId: 'com.kodecamp.certify',
  );

}