name: Build Andriod

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3
          ndk: 21.3.6528147

      - name: Install dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Debug APK
        run: |
          flutter build apk --debug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 1
